version: '3.8'

services:
  db:
    image: postgres:15
    container_name: fresh_trade_db
    environment:
      POSTGRES_DB: fresh_trade
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: fresh_trade_redis
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: fresh_trade_app
    ports:
      - "8001:8001"  # Changed to use 8001 externally and internally
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/fresh_trade
      REDIS_URL: redis://redis:6379
      SECRET_KEY: your-super-secret-key-change-this-in-production
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
    volumes:
      - ./uploads:/app/uploads
      - .:/app  # For development with hot-reload
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload

  celery:
    build: .
    container_name: fresh_trade_celery
    command: celery -A app.celery_app worker --loglevel=info  # Updated to match your actual celery app location
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/fresh_trade
      REDIS_URL: redis://redis:6379
      SECRET_KEY: your-super-secret-key-change-this-in-production

volumes:
  postgres_data: